backend:
   name: git-gateway

media_library:
  name: cloudinary
  config:
    cloud_name: tamas-demo
    api_key: 212496679715456
    output_filename_only: true
    default_transformations:
      - fetch_format: auto
        width: 400
        quality: auto
        crop: scale
collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'posts'
    create: true
    fields:
      - {
        label: 'Layout',
        name: 'layout',
        widget: 'hidden',
        default: 'layouts/post.njk',
      }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'datetime' }
      - { label: 'Author', name: 'author', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }